name: CICD
on:
  push:

jobs:
  build_app:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: hello-world
          path: dist/
