name: CICD
on:
  push:

jobs:
  build_app:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: hello-world
          path: dist/

  test_app:
    runs-on: ubuntu-latest
    container: node:14
    needs: [build_app]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run tests
        run: npm run test:unit

  e2e_tests:
    runs-on: ubuntu-latest
    needs: [test_app]
    container: testcafe/testcafe
    with:
      entrypoint: ["/bin/sh", "-c"]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --include=dev

      - name: Run e2e tests
        run: /opt/testcafe/docker/testcafe-docker.sh chromium tests/e2e.js

  deploy_app:
    runs-on: ubuntu-latest
    needs: [e2e_tests]
    steps:
      - name: Download build_app workflow run artifacts
        uses: actions/download-artifact@v2

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "hello-world-dss" #Must be unique in Heroku
          heroku_email: "alexandru.poboranu@stud.acs.upb.ro"
